/**
 * 20 launch sweet spots curated from research docs (HANDOFF + competitive teardown).
 * `tags` enable filtering by intent (transcon, premium-cabin, intra-asia, etc.).
 */

export interface SweetSpotSeed {
  programId: string;
  title: string;
  originPattern: Record<string, unknown>;
  destPattern: Record<string, unknown>;
  cabin: "Y" | "W" | "J" | "F";
  milesOneWay: number;
  approxSurchargeUsd?: number;
  notes?: string;
  sourceUrl?: string;
  curatedBy?: string;
  rank: number;
  tags: string[];
}

export const SWEET_SPOTS: SweetSpotSeed[] = [
  {
    programId: "AC_AEROPLAN",
    title: "Aeroplan 60K J to Europe (Atlantic zone)",
    originPattern: { originRegion: "NA" },
    destPattern: { destRegion: "EU" },
    cabin: "J",
    milesOneWay: 60000,
    approxSurchargeUsd: 0,
    notes: "Star Alliance partner-priced; LH/LX/SN/AC/UA available. No YQ — huge advantage over BA Avios for the same flight.",
    curatedBy: "research",
    rank: 5,
    tags: ["premium-cabin", "transatlantic", "surcharge-free"],
  },
  {
    programId: "NH_ANA",
    title: "ANA 75K F NRT-USA",
    originPattern: { originRegion: "NA" },
    destPattern: { destCountries: ["JP"] },
    cabin: "F",
    milesOneWay: 75000,
    approxSurchargeUsd: 36,
    notes: "One-way pricing via the round-trip chart applied at 50%. ANA F suite, The Room J on transpacific.",
    curatedBy: "research",
    rank: 1,
    tags: ["premium-cabin", "transpacific", "intra-asia", "surcharge-free"],
  },
  {
    programId: "AS_MILEAGEPLAN",
    title: "Alaska Cathay F USA-HKG",
    originPattern: { originRegion: "NA" },
    destPattern: { destCountries: ["HK"] },
    cabin: "F",
    milesOneWay: 70000,
    approxSurchargeUsd: 27,
    notes: "Cathay F released to Alaska; T-360 sweet spot. Stopover allowed.",
    curatedBy: "research",
    rank: 2,
    tags: ["premium-cabin", "transpacific", "stopover-friendly", "surcharge-free"],
  },
  {
    programId: "VS_FLYING_CLUB",
    title: "Virgin 50K Delta One LHR-JFK off-peak",
    originPattern: { originAirports: ["LHR"] },
    destPattern: { destAirports: ["JFK", "EWR", "BOS"] },
    cabin: "J",
    milesOneWay: 50000,
    approxSurchargeUsd: 200,
    notes: "Off-peak; peak is 57.5k. Delta One service on transatlantic.",
    curatedBy: "research",
    rank: 6,
    tags: ["premium-cabin", "transatlantic", "off-peak"],
  },
  {
    programId: "CX_CATHAY",
    title: "Cathay F HKG-JFK",
    originPattern: { originAirports: ["HKG"] },
    destPattern: { destAirports: ["JFK"] },
    cabin: "F",
    milesOneWay: 110000,
    approxSurchargeUsd: 410,
    notes: "April 2025 raised from 110k to 125k for some dates. Heavy YQ post-2026 chart change.",
    curatedBy: "research",
    rank: 7,
    tags: ["premium-cabin", "transpacific"],
  },
  {
    programId: "AV_LIFEMILES",
    title: "LifeMiles 78K J USA-Europe (Star)",
    originPattern: { originRegion: "NA" },
    destPattern: { destRegion: "EU" },
    cabin: "J",
    milesOneWay: 78000,
    approxSurchargeUsd: 0,
    notes: "Star Alliance saver — no YQ. Lufthansa F sometimes bookable at 87k.",
    curatedBy: "research",
    rank: 8,
    tags: ["premium-cabin", "transatlantic", "surcharge-free"],
  },
  {
    programId: "BA_AVIOS",
    title: "BA Avios short-haul intra-Europe 10K Y",
    originPattern: { originRegion: "EU" },
    destPattern: { destRegion: "EU" },
    cabin: "Y",
    milesOneWay: 10000,
    approxSurchargeUsd: 35,
    notes: "Short-haul economy on BA-operated. Reward Flight Saver caps cash to ~£35.",
    curatedBy: "research",
    rank: 20,
    tags: ["intra-eu", "short-haul"],
  },
  {
    programId: "UA_MP",
    title: "United Excursionist Perk on Star round trips",
    originPattern: { originRegion: "NA" },
    destPattern: { destRegion: "AS-NE" },
    cabin: "J",
    milesOneWay: 95000,
    approxSurchargeUsd: 28,
    notes: "Free one-way included via Excursionist Perk if origin and final dest are same MileagePlus region.",
    curatedBy: "research",
    rank: 12,
    tags: ["premium-cabin", "transpacific", "routing-trick"],
  },
  {
    programId: "AA_AADVANTAGE",
    title: "AAdvantage 60K J Etihad to ME",
    originPattern: { originRegion: "NA" },
    destPattern: { destAirports: ["AUH"] },
    cabin: "J",
    milesOneWay: 60000,
    approxSurchargeUsd: 27,
    notes: "Etihad J released to AA at chart pricing. Apartment availability limited; rare.",
    curatedBy: "research",
    rank: 9,
    tags: ["premium-cabin", "middle-east"],
  },
  {
    programId: "TK_MILES_SMILES",
    title: "Turkish 7.5K Y USA shorthaul (legacy chart)",
    originPattern: { originRegion: "NA" },
    destPattern: { destRegion: "NA" },
    cabin: "Y",
    milesOneWay: 7500,
    approxSurchargeUsd: 5,
    notes: "Recent move to per-segment dynamic complicates this; verify before booking.",
    curatedBy: "research",
    rank: 15,
    tags: ["short-haul", "intra-na", "fragile"],
  },
  {
    programId: "AF_FLYINGBLUE",
    title: "Flying Blue Promo Rewards (monthly)",
    originPattern: { originRegion: "NA" },
    destPattern: { destRegion: "EU" },
    cabin: "J",
    milesOneWay: 55000,
    approxSurchargeUsd: 280,
    notes: "Monthly promo dropping select routes by 25-50%. YQ still applies.",
    curatedBy: "research",
    rank: 11,
    tags: ["premium-cabin", "transatlantic", "promo"],
  },
  {
    programId: "DL_SKYMILES",
    title: "Delta SkyMiles flash sales (dynamic)",
    originPattern: { originRegion: "NA" },
    destPattern: { destRegion: "EU" },
    cabin: "J",
    milesOneWay: 75000,
    approxSurchargeUsd: 41,
    notes: "Rare sub-100k Delta One on flash sales. Otherwise 250k+.",
    curatedBy: "research",
    rank: 19,
    tags: ["premium-cabin", "transatlantic", "flash-sale"],
  },
  {
    programId: "VS_FLYING_CLUB",
    title: "Virgin 75K ANA F JFK-HND",
    originPattern: { originAirports: ["JFK", "EWR", "BOS", "IAD"] },
    destPattern: { destAirports: ["HND", "NRT"] },
    cabin: "F",
    milesOneWay: 75000,
    approxSurchargeUsd: 28,
    notes: "Virgin holds ANA partner award at chart; tighter inventory than Aeroplan but cheaper.",
    curatedBy: "research",
    rank: 4,
    tags: ["premium-cabin", "transpacific", "surcharge-free"],
  },
  {
    programId: "AC_AEROPLAN",
    title: "Aeroplan stopover for 5K extra miles",
    originPattern: { originRegion: "NA" },
    destPattern: { destRegion: "EU" },
    cabin: "J",
    milesOneWay: 65000,
    approxSurchargeUsd: 0,
    notes: "Add a stopover anywhere on the routing for +5k miles. Unique to Aeroplan.",
    curatedBy: "research",
    rank: 10,
    tags: ["premium-cabin", "stopover-friendly", "transatlantic", "surcharge-free"],
  },
  {
    programId: "CX_CATHAY",
    title: "JL F at T-360 days via Asia Miles",
    originPattern: { originAirports: ["JFK", "LAX", "ORD", "DFW", "SFO"] },
    destPattern: { destAirports: ["NRT", "HND", "KIX"] },
    cabin: "F",
    milesOneWay: 110000,
    approxSurchargeUsd: 102,
    notes: "JAL releases F to Asia Miles at T-360; consistent. Lower YQ than BA on same flight.",
    curatedBy: "research",
    rank: 3,
    tags: ["premium-cabin", "transpacific"],
  },
  {
    programId: "AS_MILEAGEPLAN",
    title: "Alaska JAL F at 70K",
    originPattern: { originRegion: "NA" },
    destPattern: { destCountries: ["JP"] },
    cabin: "F",
    milesOneWay: 70000,
    approxSurchargeUsd: 27,
    notes: "Alaska holds the cheapest JL F partner award in the market.",
    curatedBy: "research",
    rank: 2,
    tags: ["premium-cabin", "transpacific", "surcharge-free"],
  },
  {
    programId: "AC_AEROPLAN",
    title: "Aeroplan 35K Y USA-Europe (off-peak)",
    originPattern: { originRegion: "NA" },
    destPattern: { destRegion: "EU" },
    cabin: "Y",
    milesOneWay: 35000,
    approxSurchargeUsd: 0,
    notes: "Off-peak distance-based. Lufthansa, Swiss, United available.",
    curatedBy: "research",
    rank: 14,
    tags: ["transatlantic", "off-peak", "surcharge-free"],
  },
  {
    programId: "BA_AVIOS",
    title: "Avios short-haul EU-ME 17K J one-way",
    originPattern: { originRegion: "EU" },
    destPattern: { destAirports: ["AMM", "TLV"] },
    cabin: "J",
    milesOneWay: 17000,
    approxSurchargeUsd: 75,
    notes: "Royal Jordanian J on BA distance chart; underused. Pegasus chart.",
    curatedBy: "research",
    rank: 16,
    tags: ["premium-cabin", "short-haul", "middle-east"],
  },
  {
    programId: "NH_ANA",
    title: "ANA round-trip Y to Asia 55K low season",
    originPattern: { originRegion: "NA" },
    destPattern: { destRegion: "AS-NE" },
    cabin: "Y",
    milesOneWay: 27500,
    approxSurchargeUsd: 36,
    notes: "Round-trip chart 55k Y. ANA pricing favors round trips over one-ways.",
    curatedBy: "research",
    rank: 17,
    tags: ["transpacific", "round-trip-priced"],
  },
  {
    programId: "AV_LIFEMILES",
    title: "LifeMiles Lufthansa F via Star (rare)",
    originPattern: { originRegion: "NA" },
    destPattern: { destRegion: "EU" },
    cabin: "F",
    milesOneWay: 87000,
    approxSurchargeUsd: 0,
    notes: "When LH releases F to Star partners, LifeMiles charges 87k — cheapest in market.",
    curatedBy: "research",
    rank: 7,
    tags: ["premium-cabin", "transatlantic", "surcharge-free", "rare"],
  },
];
